[versions]
agp = "8.13.2"
httpclient = "1.0.4"
json = "20251224"
kotlin = "2.3.0"
kotlin-test = "2.2.0"
kotlinx-coroutines-core = "1.10.2"

[libraries]
httpclient = { module = "com.vsulimov:httpclient", version.ref = "httpclient" }
json = { module = "org.json:json", version.ref = "json" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }
